import Foundation
@main struct FoldTests {
 @MainActor static func main() throws {
  let t=TestLog()
  func ticket(_ book:inout WS2FoldEvidence, window:UInt32=1, at:Double=0)->WS2FoldEvidence.Ticket {book.begin(request:UUID(),window:window,pid:123,at:at)!}
  t.begin("FOLD01 admission is not evidence");var a=WS2FoldEvidence();let x=ticket(&a);t.check(a.contains(x),"pending");t.check(a.ticket(window:1,transaction:UUID())==nil,"no invented transaction");t.end()
  t.begin("FOLD02 hidden needs physical attempt and bound transaction");let tx=UUID();t.check(a.observe(x,transaction:tx,observation:.verifiedHidden)==nil,"no unbound success");t.check(!a.bind(x,transaction:tx),"bind before attempt refused");t.end()
  t.begin("FOLD03 exactly one ordinary completion");t.check(a.markMutation(x,at:1),"marked");t.check(a.bind(x,transaction:tx),"bound");let e=a.observe(x,transaction:tx,observation:.verifiedHidden);t.check(e?.late==false && e?.observation == .verifiedHidden,"first actual result");t.check(a.observe(x,transaction:tx,observation:.verifiedHidden)==nil && a.count==0,"no replay or retention");t.end()
  t.begin("FOLD04 wrong transaction cannot complete");var b=WS2FoldEvidence();let y=ticket(&b);_=b.markMutation(y,at:1);_=b.bind(y,transaction:tx);t.check(b.observe(y,transaction:UUID(),observation:.verifiedHidden)==nil,"foreign generation ignored");t.check(b.contains(y),"correct pending intact");t.end()
  t.begin("FOLD05 deadline before hide proves not started");var c=WS2FoldEvidence();let z=ticket(&c);let timeout=c.expire(z,at:30);t.check(timeout?.observation == .notStarted,"no attempt");t.check(!c.markMutation(z,at:31),"late screenshot cannot mutate");t.end()
  t.begin("FOLD06 deadline after hide remains unknown");var d=WS2FoldEvidence();let d1=ticket(&d);_=d.markMutation(d1,at:1);_=d.bind(d1,transaction:tx);t.check(d.expire(d1,at:30)?.observation == .unknown,"not success or false visible");t.check(d.contains(d1),"late evidence retained");t.end()
  t.begin("FOLD07 late success is marked separately");let late=d.observe(d1,transaction:tx,observation:.verifiedHidden);t.check(late?.late==true && late?.transaction==tx,"late evidence not new promise");t.check(!d.contains(d1),"finished");t.end()
  t.begin("FOLD08 early failure means no hiding attempt");var f=WS2FoldEvidence();let f1=ticket(&f);t.check(f.failed(f1)?.observation == .notStarted,"refused plan");t.check(f.count==0,"callback can release");t.end()
  t.begin("FOLD09 failure after mutation not called cancelled");let f2=ticket(&f);_=f.markMutation(f2,at:1);t.check(f.failed(f2)?.observation == .unknown,"may have hidden");t.check(f.contains(f2),"no discarded uncertainty");t.end()
  t.begin("FOLD10 error cannot turn into notStarted after write");_=f.bind(f2,transaction:tx);t.check(f.observe(f2,transaction:tx,observation:.notStarted)==nil,"forbidden downgrade");t.check(f.failed(f2)==nil,"same result not reemitted");t.end()
  t.begin("FOLD11 visible observation can later confirm hidden");var g=WS2FoldEvidence();let g1=ticket(&g);_=g.markMutation(g1,at:1);_=g.bind(g1,transaction:tx);t.check(g.observe(g1,transaction:tx,observation:.stillVisible)?.late==false,"first observation");t.check(g.observe(g1,transaction:tx,observation:.verifiedHidden)?.late==true,"async OS transition");t.end()
  t.begin("FOLD12 repeated unknown is silent");var h=WS2FoldEvidence();let h1=ticket(&h);_=h.markMutation(h1,at:1);_=h.bind(h1,transaction:tx);_=h.observe(h1,transaction:tx,observation:.unknown);t.check(h.observe(h1,transaction:tx,observation:.unknown)==nil,"no repeated notification");t.check(h.expire(h1,at:30)==nil,"old timer silent");t.end()
  t.begin("FOLD13 window-id reuse cannot consume old ticket");h.forget(h1);let h2=ticket(&h,at:31);_=h.markMutation(h2,at:32);t.check(h.observe(h1,transaction:tx,observation:.verifiedHidden)==nil,"old request ignored");t.check(h.contains(h2),"new ticket still present");t.end()
  t.begin("FOLD14 duplicate live window refused");var j=WS2FoldEvidence();_=ticket(&j);t.check(j.begin(request:UUID(),window:1,pid:123,at:1)==nil,"one current observer per window");t.check(j.count==1,"no growth");t.end()
  t.begin("FOLD15 bounded observer capacity");var k=WS2FoldEvidence();for n in 1...64{_=ticket(&k,window:UInt32(n))};t.check(k.count==64,"fixed bound");t.check(k.begin(request:UUID(),window:65,pid:123,at:0)==nil,"overflow rejected");t.end()
  t.begin("FOLD16 bad time and identifiers refused");var m=WS2FoldEvidence();t.check(m.begin(request:UUID(),window:0,pid:1,at:0)==nil,"zero window");t.check(m.begin(request:UUID(),window:1,pid:0,at:0)==nil,"zero pid");t.check(m.begin(request:UUID(),window:1,pid:1,at:.nan)==nil,"nan");t.check(m.begin(request:UUID(),window:1,pid:1,at:0,timeout:31)==nil,"timeout bound");t.check(m.begin(request:UUID(),window:1,pid:1,at:Double.greatestFiniteMagnitude)==nil,"nonadvancing deadline");t.end()
  t.begin("FOLD17 exact deadline prevents mutation");let m1=ticket(&m);t.check(m.mayStart(m1,at:29.99),"before deadline");t.check(!m.markMutation(m1,at:30),"at deadline");t.check(m.expire(m1,at:29.99)==nil,"timer cannot expire early");t.end()
  t.begin("FOLD18 second transaction cannot overwrite binding");var n=WS2FoldEvidence();let n1=ticket(&n);_=n.markMutation(n1,at:1);t.check(n.bind(n1,transaction:tx),"first bind");t.check(!n.bind(n1,transaction:UUID()),"cannot rebind newer state");t.check(n.ticket(window:1,transaction:tx)==n1,"original binding retained");t.end()
  t.begin("FOLD19 callback after bounded release is inert");n.forget(n1);t.check(n.observe(n1,transaction:tx,observation:.verifiedHidden)==nil,"no stale callback");t.check(n.count==0,"storage released");t.end()
  t.begin("FOLD20 forged ticket cannot use matching request UUID");var p=WS2FoldEvidence();let p1=ticket(&p);let forged=WS2FoldEvidence.Ticket(request:p1.request,window:999,pid:123);t.check(!p.markMutation(forged,at:1),"window mismatch");t.check(p.failed(forged)==nil,"full ticket checked");t.end()
  t.begin("FOLD21 backward time cannot start mutation");var q=WS2FoldEvidence();let q1=ticket(&q,at:10);t.check(!q.markMutation(q1,at:9),"before creation refused");t.check(q.markMutation(q1,at:10),"created now allowed");t.end()
  try t.save(URL(fileURLWithPath:CommandLine.arguments[1]))
 }
}
