import Foundation


@main
struct AgentSessionsTests {
    static func main() {
        var t = TestSuite("A1")

        func env(_ context:WS2.Context,_ seq:UInt64,_ at:Double,_ event:AgentSessions.Event,turn:String?=nil)->WS2.Envelope<AgentSessions.Event> {
            .init(context:context,sequence:seq,receivedAt:sec(at),commandID:nil,turnID:turn,payload:event)
        }
        let c=fixtureContext()
        t.section("A1-01", "同项目不同会话、不同助手同 ID → 三条独立记录")
        var a=AgentSessions()
        _=a.receive(env(c,1,0,.opened(.owned))); let c2=fixtureContext(session:"session-2");let c3=fixtureContext(provider:.claudeCode)
        _=a.receive(env(c2,1,0,.opened(.observed)));_=a.receive(env(c3,1,0,.opened(.observed)))
        t.expect(a.sessions.count==3,"不按目录或显示名合并")
        t.section("A1-02", "工具前后、停止 → 在跑、完成；工具重放不累积")
        _=a.receive(env(c,2,1,.prompt(summary:"测试")));_=a.receive(env(c,3,2,.toolStarted(id:"tool-1",summary:"读文件")))
        _=a.receive(env(c,4,3,.toolStarted(id:"tool-1",summary:"重复")))
        t.expect(a.sessions[c.session]?.tools.count==1,"工具幂等")
        _=a.receive(env(c,5,4,.toolFinished(id:"tool-1")));_=a.receive(env(c,6,5,.turnFinished(summary:"改了 1 个文件")))
        t.expect(a.sessions[c.session]?.status == .completed && a.sessions[c.session]?.tools.isEmpty == true,"完成归档")
        t.section("A1-03", "普通审批新点按 → 只发授权意图；重复确认和错摘要结果不清请求")
        var b=AgentSessions();_=b.receive(env(c,1,0,.opened(.owned))); let req=fixtureApproval()
        _=b.receive(env(c,2,1,.approval(req)))
        t.expect(b.choose(req.key,choice:.confirm,beganAt:sec(0.9),sequence:3,now:sec(1.1)).isEmpty,"旧 down 不能放行")
        let ask=b.choose(req.key,choice:.confirm,beganAt:sec(1.2),sequence:3,now:sec(1.3))
        t.expect(ask.contains(where:{if case .requestAuthorization=$0{return true};return false}),"请求唯一授权服务")
        t.expect(b.choose(req.key,choice:.confirm,beganAt:sec(1.4),sequence:4,now:sec(1.5)).isEmpty,"不重复申请")
        _=b.authorizationFinished(.dispatched(key:req.key,targetDigest:digest(2)),now:sec(2))
        t.expect(b.approvalCount==1,"错目标通知无效")
        let done=b.authorizationFinished(.dispatched(key:req.key,targetDigest:digest()),now:sec(2.1))
        t.expect(b.approvalCount==0 && !done.contains(where:{if case .finishApproval=$0{return true};return false}),"已由服务应答，不再回第二次")
        t.section("A1-04", "整数7与字符串7 → 两次独立审批；返回只否定眼前一件")
        var d=AgentSessions();_=d.receive(env(c,1,0,.opened(.owned)))
        let i=fixtureApproval(id:.integer(7),seq:2),s=fixtureApproval(id:.string("7"),seq:3)
        _=d.receive(env(c,2,1,.approval(i)));_=d.receive(env(c,3,1.1,.approval(s)))
        t.expect(d.approvalCount==2,"ID 类型不能转字符串混合")
        t.expect(d.choose(i.key,choice:.deny,beganAt:sec(2),sequence:4,now:sec(2)).contains(.finishApproval(i.key,.deny)) && d.approvalCount==1,"只拒绝当前 ID")
        t.section("A1-05", "两分钟期限/更短宿主期限/迟到确认 → 到点交回，不默许")
        var e=AgentSessions();_=e.receive(env(c,1,0,.opened(.owned)))
        let long=fixtureApproval(end:999);_=e.receive(env(c,2,1,.approval(long)))
        t.expect(e.request(for:long.key)?.deadline==sec(121),"120秒上限")
        t.expect(e.tick(at:sec(121)).contains(.finishApproval(long.key,.deferToHost)),"到期交回")
        t.expect(e.choose(long.key,choice:.confirm,beganAt:sec(122),sequence:4,now:sec(122)).isEmpty,"迟到不批准")
        var short=AgentSessions();_=short.receive(env(c,1,0,.opened(.owned)))
        let shortReq=fixtureApproval(end:6);_=short.receive(env(c,2,1,.approval(shortReq)))
        t.expect(short.tick(at:sec(6)).contains(.finishApproval(shortReq.key,.deferToHost)),"较短宿主期限优先")
        t.section("A1-06", "600秒没事件 → 信息已久；明确进程退出 → 断开")
        var f=AgentSessions();_=f.receive(env(c,1,0,.opened(.observed)));_=f.tick(at:sec(600))
        t.expect(f.sessions[c.session]?.status == .stale,"无消息不是断线")
        _=f.receive(env(c,2,601,.processExited));t.expect(f.sessions[c.session]?.status == .disconnected,"明确退出才断")
        _=f.receive(env(c,3,602,.prompt(summary:"退出后的旧回调")))
        t.expect(f.sessions[c.session]?.status == .disconnected,"旧进程不能复活")
        t.section("A1-07", "乱序和重连旧 epoch → 不更改当前会话，不保留旧审批")
        var g=AgentSessions();_=g.receive(env(c,1,0,.opened(.owned)));_=g.receive(env(c,2,1,.approval(req)))
        t.expect(g.receive(env(c,2,1.1,.prompt(summary:"重放"))).contains(.fault(.sequenceReplayed)),"重复序号拒绝")
        let newer=fixtureContext(epoch:2);_=g.receive(env(newer,1,2,.opened(.owned)))
        t.expect(g.approvalCount==0,"重连撤旧审批")
        t.expect(g.receive(env(c,3,3,.prompt(summary:"旧会话"))).contains(.fault(.staleContext)),"旧代次拒绝")
        t.section("A1-08", "同请求号换摘要 → 撤旧请求并交回，不能沿用已确认动作")
        var h=AgentSessions();_=h.receive(env(c,1,0,.opened(.owned)));_=h.receive(env(c,2,1,.approval(req)))
        let collision=fixtureApproval(seq:3,target:2)
        let conflict=h.receive(env(c,3,2,.approval(collision)))
        t.expect(h.approvalCount==0 && conflict.contains(.fault(.malformedInput)),"碰撞不覆盖旧目标")
        t.section("A1-09", "锁屏后事件到来 → 展示为空，敏感摘要清掉，审批交回")
        var j=AgentSessions();_=j.receive(env(c,1,0,.opened(.owned)));_=j.receive(env(c,2,1,.approval(req)))
        t.expect(j.suspend(at:sec(2)).contains(.finishApproval(req.key,.deferToHost)),"锁屏撤销审批")
        _=j.receive(env(c,3,3,.prompt(summary:"秘密草稿")))
        t.expect(j.visibleSessions.isEmpty && j.sessions[c.session]?.summary == "","不在锁屏留标题摘要")
        t.expect(j.resume(at:sec(4)).contains(.requestSnapshot(c)),"解锁查询现状，不重播审批")
        t.section("A1-10", "超出会话/请求容量 → 报容量并交回，不能挤掉待审批项目")
        var bounded=AgentSessions()
        for k in 0..<64 {_=bounded.receive(env(fixtureContext(session:"s\(k)"),1,0,.opened(.owned)))}
        t.expect(bounded.receive(env(fixtureContext(session:"overflow"),1,1,.opened(.owned))).contains(.fault(.capacityExceeded)) && bounded.sessions.count==64,"会话上限")
        var requests=AgentSessions();_=requests.receive(env(c,1,0,.opened(.owned)))
        for k in 0..<8 {let q=fixtureApproval(id:.integer(Int64(k)),seq:UInt64(k+2));_=requests.receive(env(c,UInt64(k+2),1+Double(k)/100,.approval(q)))}
        let over=fixtureApproval(id:.integer(99),seq:10)
        t.expect(requests.receive(env(c,10,2,.approval(over))).contains(.finishApproval(over.key,.deferToHost)) && requests.approvalCount==8,"不驱逐已有审批")
        t.section("A1-11", "风险类型明确或 shell 未知 → 高风险/未知不降成普通")
        t.expect(AgentSessions.risk(of:.readWorkspace) == .normal && AgentSessions.risk(of:.runDeclaredTests) == .normal,"明确声明的普通动作")
        t.expect(AgentSessions.risk(of:.shell) == .unknown && AgentSessions.risk(of:.delete) == .high && AgentSessions.risk(of:.network) == .high,"不靠 shell 前缀")

        t.finish()
    }
}
