import Foundation
@main
struct ContractsTests {
    static func main() throws {
        var t=TestSuite("CONTRACTS")
        t.section("C-01", "时间单位转换拒绝负数/NaN/无穷/溢出，最大加法不回绕")
        t.expect(WS2.Instant(seconds:-1)==nil && WS2.Instant(seconds:.nan)==nil && WS2.Instant(seconds:.infinity)==nil,"拒绝非法秒")
        t.expect(WS2.Instant(seconds:Double(UInt64.max))==nil,"拒绝溢出秒")
        t.expect(sec(1).nanoseconds==1_000_000_000,"明确纳秒")
        t.expect(WS2.Instant(nanoseconds:.max-2).adding(4).nanoseconds == .max,"饱和而不回绕")
        t.section("C-02", "同刻事件允许，时间倒流拒绝而不更新上次时间")
        var time=WS2.TimeGate();t.expect(time.accept(sec(2)) && time.accept(sec(2)),"同刻可处理多个事件")
        t.expect(!time.accept(sec(1)) && time.last==sec(2),"失败不回写时钟")
        t.section("C-03", "共享总线序号可有空洞，不允许重放、零或新序号配旧时间")
        var gate=WS2.EventGate();t.expect(!gate.accept(sequence:0,at:sec(0)),"零序号无效")
        t.expect(gate.accept(sequence:4,at:sec(1)) && gate.accept(sequence:9,at:sec(1)),"空洞与同刻合法")
        t.expect(!gate.accept(sequence:9,at:sec(2)) && !gate.accept(sequence:10,at:sec(0)),"重放和倒流拒绝")
        t.expect(gate.lastSequence==9 && gate.lastTime==sec(1),"拒绝不污染下一条")
        t.section("C-04", "同一boot不同组件的1号token不得相等，源内编号递增")
        var timer=WS2.TokenSource(bootID:fixtureBoot,domain:.focusTimer)
        var presence=WS2.TokenSource(bootID:fixtureBoot,domain:.presenceLock)
        let one=timer.next()!,other=presence.next()!,two=timer.next()!
        t.expect(one != other && one.serial==1 && other.serial==1,"组件编号域隔离")
        t.expect(two.serial==2 && two != one,"源内递增")
        let tokenRoundTrip = try JSONDecoder().decode(WS2.Token.self,from:JSONEncoder().encode(one))
        t.expect(tokenRoundTrip==one,"令牌往返不丢domain")
        t.section("C-05", "摘要只接受32字节，JSON解码也不能绕过")
        t.expect(WS2.Digest(Data(repeating:0,count:31))==nil && WS2.Digest(Data(repeating:0,count:33))==nil,"长度检查")
        let encoded=try JSONEncoder().encode(Data(repeating:0,count:31))
        t.expect((try? JSONDecoder().decode(WS2.Digest.self,from:encoded))==nil,"恶意decode拒绝")
        let digestRoundTrip = try JSONDecoder().decode(WS2.Digest.self,from:JSONEncoder().encode(digest()))
        t.expect(digestRoundTrip==digest(),"正确摘要往返")
        t.section("C-06", "RPC整数7和字符串7、不同provider的同session分别存储")
        t.expect(WS2.RequestID.integer(7) != .string("7"),"请求号不转字符串")
        t.expect(fixtureContext().session != fixtureContext(provider:.claudeCode).session,"提供商属于会话身份")
        t.section("C-07", "空标识、超长字节、审批上下文错配与空摘要展示拒绝")
        t.expect(!fixtureContext(peer:"").isValid && !fixtureContext(project:String(repeating:"中",count:1400)).isValid,"实际UTF8字节上限")
        let bad=WS2.ApprovalRequest(key:.init(session:fixtureContext().session,epoch:99,requestID:.integer(1)),context:fixtureContext(),targetDigest:digest(),summary:"test",risk:.normal,createdAt:sec(1),deadline:sec(2),shownAfterSequence:1)
        t.expect(!bad.isValid,"错epoch不接受")
        t.expect(!fixtureApproval(created:2,end:2).isValid,"零期限拒绝")
        t.section("C-08", "六层顺序固定、展示快照不含私密正文")
        t.expect(WS2.Layer.allCases.sorted().map(\.rawValue)==[1,2,3,4,5,6],"小数字优先")
        let snap=WS2.VisibilitySnapshot(display:.init(value:1),environmentEpoch:2,layer:.ongoing,lease:nil,ongoingIDs:["test-id"],hasSecondaryDot:false)
        t.expect(snap.lease==nil && snap.ongoingIDs==["test-id"],"静态ID快照，不传秘密全文")
        t.section("C-09", "真实连续时钟只验证同进程不倒流，不声称测过睡眠")
        let clock=WS2ContinuousClock();let a=clock.now();let b=clock.now()
        t.expect(b>=a,"同一实例时钟单调")
        t.finish()
    }
}
