import Foundation

@main
struct FocusTimerTests {
    static func main() {
        var t = TestSuite("T1")

        let cal = FocusTimer.CalendarSample(today: "2026-10-03", deadlineDay: "2026-10-03")
        t.section("T1-01", "空闲开始 25+5 → 截止时刻 1500 秒，聊天收起一次")
        var a = FocusTimer(bootID: fixtureBoot)
        t.expect(a.nextWake(at: sec(0), presentation: .compact) == nil, "空闲不排刷新")
        let start = a.handle(.start, at: sec(0), calendar: cal)
        t.expect(a.phase == .focus && a.deadline == sec(1500), "开始不是累计 tick")
        t.expect(start.count == 1 && a.handle(.start, at: sec(0), calendar: cal).isEmpty, "重复开始无重复窗口动作")
        t.section("T1-02", "紧凑/展开/隐藏 → 分别排分钟、秒、截止唤醒")
        t.expect(a.nextWake(at: sec(0), presentation: .compact) == sec(60), "紧凑整分钟")
        t.expect(a.nextWake(at: sec(0), presentation: .expanded) == sec(1), "展开一秒")
        t.expect(a.nextWake(at: sec(0), presentation: .hidden) == sec(1500), "隐藏只有到点")
        t.expect(a.compactText(at: sec(420)) == "18 分", "18 分原文")
        t.expect(a.compactText(at: sec(1458)) == "0:42", "最后一分钟秒数")
        t.expect(a.nextWake(at: sec(1458.25), presentation: .compact) == sec(1459), "秒显示与截止对齐")
        t.section("T1-03", "专注自然到点再休息到点 → 计数一次，不自动下一轮")
        let focusEnd = a.handle(.tick, at: sec(1500), calendar: cal)
        t.expect(a.phase == .rest && a.completedToday == 1 && a.deadline == sec(1800), "完整专注才计数")
        t.expect(focusEnd.contains(.sound(.restStarted)), "真实到点提示音")
        let restEnd = a.handle(.tick, at: sec(1800), calendar: cal)
        t.expect(a.phase == .idle && restEnd.contains(.sound(.restFinished)), "休息完空闲")
        t.expect(a.handle(.tick, at: sec(1800), calendar: cal).isEmpty, "重复 tick 无补发")
        t.section("T1-04", "手动暂停叠加锁屏 → 单独继续不解除锁屏暂停")
        var b = FocusTimer(bootID: fixtureBoot)
        _ = b.handle(.start, at: sec(0), calendar: cal)
        _ = b.handle(.pause, at: sec(10), calendar: cal)
        _ = b.handle(.locked, at: sec(20), calendar: cal)
        _ = b.handle(.resume, at: sec(30), calendar: cal)
        t.expect(b.isPaused && b.pauses == [.locked] && b.remaining(at: sec(40)) == 1490 * WS2.Duration.second, "暂停原因独立")
        t.expect(b.nextWake(at: sec(40), presentation: .expanded) == nil, "暂停不醒来")
        _ = b.handle(.unlocked, at: sec(50), calendar: cal)
        t.expect(b.deadline == sec(1540), "正确顺延剩余时间")
        t.section("T1-05", "睡眠叠加锁屏，先唤醒后解锁 → 最后一个原因解除才计时")
        _ = b.handle(.sleep, at: sec(60), calendar: cal)
        _ = b.handle(.locked, at: sec(70), calendar: cal)
        _ = b.handle(.wake, at: sec(80), calendar: cal)
        t.expect(b.pauses == [.locked], "唤醒不能解锁")
        _ = b.handle(.unlocked, at: sec(100), calendar: cal)
        t.expect(b.deadline == sec(1580), "睡眠期间无扣秒")
        t.section("T1-06", "休息睡两小时 → 已结束，不补播开始或结束音")
        var c = FocusTimer(bootID: fixtureBoot)
        _ = c.handle(.start, at: sec(0), calendar: cal); _ = c.handle(.tick, at: sec(1500), calendar: cal)
        _ = c.handle(.sleep, at: sec(1510), calendar: cal)
        let wake = c.handle(.wake, at: sec(8710), calendar: cal)
        t.expect(c.phase == .idle && !wake.contains(.sound(.restFinished)) && !wake.contains(.sound(.restStarted)), "休息不因睡眠冻结")
        t.section("T1-07", "专注到点同刻锁屏 → 结算次数，但不收全桌面、不响铃")
        var d = FocusTimer(bootID: fixtureBoot)
        _ = d.handle(.start, at: sec(0), calendar: cal)
        let locked = d.handle(.locked, at: sec(1500), calendar: cal)
        t.expect(d.completedToday == 1 && d.phase == .rest, "已完成专注仍计数")
        t.expect(!locked.contains(where: { if case .tuckAll = $0 { return true }; if case .sound = $0 { return true }; return false }), "锁屏先于可见效果")
        t.section("T1-08", "专注跳过和主动结束 → 都不增加完成数")
        var e = FocusTimer(bootID: fixtureBoot)
        _ = e.handle(.start, at: sec(0), calendar: cal); _ = e.handle(.skip, at: sec(3), calendar: cal)
        t.expect(e.phase == .rest && e.completedToday == 0, "跳过不算完成")
        _ = e.handle(.end, at: sec(4), calendar: cal)
        t.expect(e.phase == .idle, "结束清理")
        _ = e.handle(.start, at: sec(5), calendar: cal); _ = e.handle(.end, at: sec(1505), calendar: cal)
        t.expect(e.completedToday == 0, "明确结束优先于同刻自然结束")
        t.section("T1-09", "休息关掉收起的窗口 → 计时继续，恢复只发一次")
        var f = FocusTimer(bootID: fixtureBoot)
        _ = f.handle(.start, at: sec(0), calendar: cal); _ = f.handle(.tick, at: sec(1500), calendar: cal)
        let restore = f.handle(.dismissRestWindows, at: sec(1510), calendar: cal)
        t.expect(f.phase == .rest && restore.count == 1, "只撤销本轮窗口归属")
        t.expect(f.handle(.dismissRestWindows, at: sec(1511), calendar: cal).isEmpty, "重复关闭无动作")
        t.section("T1-10", "旧日期的 deadline 晚到新日期 → 不记到今天，不闪过已过去的休息")
        var g = FocusTimer(bootID: fixtureBoot)
        _ = g.handle(.start, at: sec(0), calendar: cal)
        let late = g.handle(.tick, at: sec(4000), calendar: .init(today: "2026-10-04", deadlineDay: "2026-10-03"))
        t.expect(g.completedToday == 0 && g.phase == .idle && !late.contains(where: { if case .tuckAll = $0 { return true }; return false }), "晚到不补播")
        t.section("T1-11", "50+10，关闭聊天收起 → 3000 秒专注、600 秒休息")
        var h = FocusTimer(bootID: fixtureBoot, preset: .minutes50, tuckChatEnabled: false)
        t.expect(h.handle(.start, at: sec(0), calendar: cal).isEmpty && h.deadline == sec(3000), "关闭选项不收聊天")
        _ = h.handle(.tick, at: sec(3000), calendar: cal)
        t.expect(h.deadline == sec(3600), "十分钟休息")
        t.section("T1-12", "时间倒流/无效日期/锁屏开始 → 拒绝，不启动第二轮")
        t.expect(h.handle(.tick, at: sec(1), calendar: cal) == [.fault(.timeReversed)], "拒绝倒流")
        var z = FocusTimer(bootID: fixtureBoot)
        _ = z.handle(.locked, at: sec(0), calendar: cal)
        t.expect(z.handle(.start, at: sec(1), calendar: cal).isEmpty && z.phase == .idle, "锁着不开始")
        t.expect(z.handle(.start, at: sec(2), calendar: .init(today: "", deadlineDay: "")) == [.fault(.malformedInput)], "日期不可伪空")

        t.finish()
    }
}
