import Foundation
#if canImport(Darwin)
import Darwin
#else
import Glibc
#endif

@main struct FlowTests {
    @MainActor static func main() async throws {
        let t=TestLog(),fixture=URL(fileURLWithPath:CommandLine.arguments[1])
        let root=FileManager.default.temporaryDirectory.resolvingSymlinksInPath().appendingPathComponent("ws2-part7-flow-"+UUID().uuidString,isDirectory:true)
        try FileManager.default.createDirectory(at:root,withIntermediateDirectories:true,attributes:[.posixPermissions:0o700])
        defer { try? FileManager.default.removeItem(at:root) }
        var controllers:[WS2OwnedLaunchController]=[]
        func make(_ mode:String) throws -> (WS2OwnedLaunchController,URL,URL) {
            let base=root.appendingPathComponent(mode+"-"+UUID().uuidString,isDirectory:true)
            let project=base.appendingPathComponent("project",isDirectory:true)
            try FileManager.default.createDirectory(at:project,withIntermediateDirectories:true,attributes:[.posixPermissions:0o700])
            let exe=base.appendingPathComponent("fake-codex-"+mode+".py")
            try Data(contentsOf:fixture).write(to:exe)
            try FileManager.default.setAttributes([.posixPermissions:0o700],ofItemAtPath:exe.path)
            let c=WS2OwnedLaunchController(profileRoot:base.appendingPathComponent("state",isDirectory:true),mayUse:{true})
            controllers.append(c)
            t.check(c.selectProject(project),"select real temporary directory")
            t.check(c.selectExecutable(exe),"select fixture executable")
            return (c,project,exe)
        }
        func start(_ c:WS2OwnedLaunchController,diagnostics:Bool=false) async {
            t.check(c.launch(consent:true,diagnostics:diagnostics),"launch accepted")
            let ready=await until({c.phase == .ready || c.phase == .signedOut || c.phase == .failed || c.phase == .stopped})
            t.check(ready,"initial handshake terminates")
        }
        func shutdown(_ c:WS2OwnedLaunchController) async {
            c.stop();let ended=await until({!c.isBusy});t.check(ended,"native reaping finished")
        }
        t.begin("FLOW01 local launch and actual stream completion")
        let (c,_,exe)=try make("normal")
        t.check(!c.launch(consent:false),"no consent no process")
        t.check(c.store.visibleSessions.isEmpty,"no fake initial session")
        await start(c)
        t.check(c.phase == .ready,"config and account confirmed")
        t.check(c.models.keys.sorted()==["fixture-a"],"actual catalogue")
        t.check(c.store.visibleSessions.isEmpty,"still no backend thread")
        t.check(!c.chooseModel("invented-model"),"no invented model")
        t.check(c.chooseModel("fixture-a"),"select real model")
        t.check(!c.send("你好",hasMarkedText:true),"IME composition never submits")
        t.check(c.send("你好",hasMarkedText:false),"one explicit submission")
        t.check(!c.send("重复",hasMarkedText:false),"cannot duplicate while pending")
        let complete=await until({c.phase == .completed});t.check(complete,"matched final notification")
        t.check(c.text.contains("真实管道回复"),"actual stdout connected to view projection")
        t.check(!c.text.contains("WRONG-TARGET"),"foreign thread delta ignored")
        t.check(c.store.visibleSessions.first?.status == .completed,"existing store updated")
        let originalID=c.session!.connectionID
        await shutdown(c)
        t.check(c.observedReaps==1,"reap is separate fact")
        let messages=try String(contentsOf:exe.deletingPathExtension().appendingPathExtension("messages.ndjson"),encoding:.utf8)
        t.check(messages.contains("config/read") && messages.contains("account/read") && messages.contains("thread/start") && messages.contains("turn/start"),"all real pipe boundaries visited")
        t.end()
        t.begin("FLOW02 resume only the locally associated project")
        await start(c);t.check(c.session?.connectionID != originalID,"fresh connection")
        t.check(c.chooseModel("fixture-a"),"real model on new connection")
        t.check(c.canResume,"matching local thread association")
        t.check(c.resumeLast(),"explicit resume")
        let resumed=await until({c.phase == .ready && c.store.visibleSessions.first?.status == .idle})
        t.check(resumed,"resume yields actual owned thread")
        await shutdown(c);t.end()
        t.begin("FLOW03 different project cannot reuse old thread")
        let other=root.appendingPathComponent("other",isDirectory:true);try FileManager.default.createDirectory(at:other,withIntermediateDirectories:true)
        t.check(c.selectProject(other),"select different real project");await start(c)
        t.check(c.chooseModel("fixture-a"),"select model");t.check(!c.canResume,"cross-project resume denied")
        await shutdown(c);t.end()
        t.begin("FLOW04 actual login response and exact login ID")
        let (login,_,_)=try make("login");var opened:[URL]=[];login.onBrowserURL={opened.append($0)}
        await start(login);t.check(login.phase == .signedOut,"signed out fact")
        t.check(login.login(),"explicit login action")
        let authenticated=await until({login.phase == .ready});t.check(authenticated,"login completed then account/read")
        t.check(opened.count==1 && opened[0].host=="auth.openai.com","one bounded browser handoff")
        t.check(login.logout(),"logout request")
        let loggedOut=await until({!login.isBusy});t.check(loggedOut,"logout closes and reaps");t.end()
        t.begin("FLOW05 interrupt RPC is not final completion")
        let (hold,_,_)=try make("hold");await start(hold);t.check(hold.chooseModel("fixture-a"),"model")
        t.check(hold.send("停在这里",hasMarkedText:false),"send")
        let running=await until({hold.phase == .running});t.check(running,"turn observed")
        t.check(hold.interrupt(),"interrupt request")
        try? await Task.sleep(nanoseconds:50_000_000)
        t.check(hold.phase == .interrupting,"RPC response alone cannot complete")
        let interrupted=await until({hold.status=="助手已停止"});t.check(interrupted,"matched interrupted final event")
        t.check(hold.store.visibleSessions.first?.summary=="已停止","not false success")
        await shutdown(hold);t.end()
        t.begin("FLOW06 elevation always declined by local entry")
        let (approval,_,approvalExe)=try make("approval");await start(approval);_=approval.chooseModel("fixture-a")
        t.check(approval.send("查询",hasMarkedText:false),"send")
        let done=await until({approval.phase == .completed});t.check(done,"backend received decline")
        t.check(approval.notice.contains("已拒绝"),"visible decline")
        await shutdown(approval)
        let approvalLog=try String(contentsOf:approvalExe.deletingPathExtension().appendingPathExtension("messages.ndjson"),encoding:.utf8)
        t.check(approvalLog.contains("decline") && !approvalLog.contains("\"accept\""),"no allow serialization in local profile")
        t.end()
        t.begin("FLOW07 failed turn is not successful completion")
        let (failed,_,_)=try make("failed");await start(failed);_=failed.chooseModel("fixture-a");_=failed.send("失败测试",hasMarkedText:false)
        let failure=await until({failed.phase == .failed});t.check(failure,"failed final event")
        t.check(failed.store.visibleSessions.first?.status == .failed,"store failure")
        await shutdown(failed);t.end()
        for (name,mode) in [("FLOW08 mismatched version","version"),("FLOW09 effective config mismatch","config"),("FLOW10 duplicate raw JSON","duplicate")] {
            t.begin(name);let (bad,_,badExe)=try make(mode);await start(bad)
            t.check(bad.phase != .ready && bad.phase != .signedOut,"not admitted")
            await shutdown(bad)
            let path=badExe.deletingPathExtension().appendingPathExtension("messages.ndjson")
            let log=(try? String(contentsOf:path,encoding:.utf8)) ?? ""
            t.check(!log.contains("thread/start") && !log.contains("turn/start"),"no work request on failed admission");t.end()
        }
        t.begin("FLOW11 reject arbitrary auth URL")
        let (url,_,_)=try make("url");var browserCount=0;url.onBrowserURL={_ in browserCount += 1}
        await start(url);t.check(url.login(),"login attempt")
        let endedURL=await until({!url.isBusy});t.check(endedURL,"bad auth response closes")
        t.check(browserCount==0,"never opened file URL");t.end()
        t.begin("FLOW12 unrelated login completion cannot authenticate")
        let (wrong,_,_)=try make("login-wrong-id");await start(wrong);_=wrong.login()
        try? await Task.sleep(nanoseconds:120_000_000)
        t.check(wrong.phase == .signedOut,"wrong login ID ignored")
        wrong.cancelLogin();await shutdown(wrong);t.end()
        t.begin("FLOW13 project replacement invalidates submission")
        let (directory,project,_)=try make("directory");await start(directory);_=directory.chooseModel("fixture-a")
        let saved=project.deletingLastPathComponent().appendingPathComponent("old-project")
        try FileManager.default.moveItem(at:project,to:saved)
        try FileManager.default.createDirectory(at:project,withIntermediateDirectories:false)
        t.check(!directory.send("不要写入新目录",hasMarkedText:false),"directory identity changed")
        await shutdown(directory);t.end()
        t.begin("FLOW14 actual lock invalidation and no automatic restart")
        let base=root.appendingPathComponent("lock",isDirectory:true),projectLock=base.appendingPathComponent("project",isDirectory:true)
        try FileManager.default.createDirectory(at:projectLock,withIntermediateDirectories:true)
        let lockExe=base.appendingPathComponent("fake-codex-lock.py");try Data(contentsOf:fixture).write(to:lockExe)
        try FileManager.default.setAttributes([.posixPermissions:0o700],ofItemAtPath:lockExe.path)
        var unlocked=true
        let lock=WS2OwnedLaunchController(profileRoot:base.appendingPathComponent("state"),mayUse:{unlocked});controllers.append(lock)
        _=lock.selectProject(projectLock);_=lock.selectExecutable(lockExe);await start(lock);_=lock.chooseModel("fixture-a")
        _=lock.editDraft("仅内存私密草稿");_=lock.send("锁定测试",hasMarkedText:false)
        let lockRunning=await until({lock.phase == .running});t.check(lockRunning,"running before lock")
        unlocked=false;lock.environmentChanged()
        t.check(lock.text.isEmpty && lock.draft.isEmpty && lock.store.visibleSessions.isEmpty,"private views cleared")
        let lockEnded=await until({!lock.isBusy});t.check(lockEnded,"reaped after revoke")
        unlocked=true;lock.environmentChanged();t.check(lock.session==nil,"unlock does not resume")
        t.end()
        t.begin("FLOW15 diagnostics are opt-in and clearable")
        let (diagnostics,_,_)=try make("diagnostics");await start(diagnostics,diagnostics:true);_=diagnostics.chooseModel("fixture-a")
        _=diagnostics.send("诊断",hasMarkedText:false)
        let sawDiagnostics=await until({diagnostics.diagnostics.contains("fixture stderr")});t.check(sawDiagnostics,"real stderr retained only when requested")
        await shutdown(diagnostics);diagnostics.stop(clearPrivate:true)
        t.check(diagnostics.diagnostics.isEmpty,"privacy clear after stop")
        t.end()
        t.begin("FLOW16 version-probe cancellation still awaits reaping")
        let (cancelProbe,_,_)=try make("version-hang")
        t.check(cancelProbe.launch(consent:true),"version probe starts")
        try? await Task.sleep(nanoseconds:100_000_000)
        cancelProbe.stop(clearPrivate:true)
        t.check(cancelProbe.isBusy,"closing probe cannot be replaced before reap")
        t.check(!cancelProbe.launch(consent:true),"second probe cannot overlap cleanup")
        let probeClosed=await until({!cancelProbe.isBusy});t.check(probeClosed,"cancelled probe finally reaped")
        t.end()
        t.begin("FLOW17 version timeout does not invent a reap receipt")
        let (timeoutProbe,_,_)=try make("version-hang")
        t.check(timeoutProbe.launch(consent:true),"probe starts")
        let probeFailed=await until({!timeoutProbe.isBusy})
        t.check(probeFailed && timeoutProbe.phase == .failed,"timeout and cleanup precede final failure")
        t.check(timeoutProbe.session==nil,"never starts app server after bad version probe");t.end()
        t.begin("FLOW18 login cancellation requires fresh account verification")
        let (cancelLogin,_,_)=try make("login-cancel");await start(cancelLogin)
        t.check(cancelLogin.login(),"explicit login")
        try? await Task.sleep(nanoseconds:100_000_000)
        cancelLogin.cancelLogin()
        t.check(!cancelLogin.canLogin,"no overlapping replacement login")
        let cancelled=await until({!cancelLogin.isBusy});t.check(cancelled,"cancel closes and reaps before reuse")
        t.check(!cancelLogin.canSend,"cancel callback is not authentication");t.end()
        var wire=Data()
        if let items=FileManager.default.enumerator(at:root,includingPropertiesForKeys:nil) {
            // Swift 6：异步上下文里不能直接迭代 NSEnumerator，先落成数组再筛。
            for url in items.compactMap({ $0 as? URL }) where url.lastPathComponent.hasSuffix(".messages.ndjson") {
                wire.append(try Data(contentsOf:url))
            }
        }
        try wire.write(to:URL(fileURLWithPath:CommandLine.arguments[2]).deletingLastPathComponent().appendingPathComponent("flow-outbound.ndjson"))
        try t.save(URL(fileURLWithPath:CommandLine.arguments[2]))
    }
}
