import Foundation
#if canImport(Darwin)
import Darwin
#else
import Glibc
#endif
@main @MainActor struct Part3Tests {
    static var scenarios = 0, assertions = 0, failures = 0
    static var output: [[String:Any]] = []
    static func check(_ value:Bool,_ text:String) { assertions += 1; if !value { failures += 1; print("FAIL \(text)") } }
    static func rejects(_ text:String,_ body:() throws -> Void) {
        do { try body(); check(false,text) } catch { check(true,text) }
    }
    static func scenario(_ name:String,_ body:() throws -> Void) {
        let before = failures, prior = assertions; scenarios += 1
        do { try body() } catch { failures += 1; print("ERROR \(name): \(error)") }
        output.append(["name":name,"assertions":assertions-prior,"passed":failures == before])
        print("\(failures == before ? "PASS" : "FAIL") \(name)")
    }
    static func main() throws {
        let root = URL(fileURLWithPath:CommandLine.arguments[1])
        let temp = URL(fileURLWithPath:NSTemporaryDirectory()).resolvingSymlinksInPath().appendingPathComponent("ws2-"+UUID().uuidString)
        try FileManager.default.createDirectory(at:temp,withIntermediateDirectories:false,attributes:[.posixPermissions:0o700])
        defer { try? FileManager.default.removeItem(at:temp) }
        scenario("gamepad-default-off") { var m = GamepadMapping(); check(m.sample(left:.init(x:1,y:1),right:.zero,at:1).isEmpty,"no effect"); check(m.trigger(left:true,value:1,desktopEnabled:true).isEmpty,"no desktop") }
        scenario("gamepad-radial-deadzone-and-finite") { check(GamepadMapping.axis(.init(x:0.1,y:0.1)) == .zero,"dead zone"); check(GamepadMapping.axis(.init(x:.nan,y:1)) == .zero,"nan"); let a = GamepadMapping.axis(.init(x:1,y:1)); check(abs(hypot(a.x,a.y)-1)<1e-9,"diagonal capped") }
        scenario("gamepad-first-sample-no-jump") { var m = GamepadMapping(); _=m.configure(enabled:true,gameInFront:false); check(m.sample(left:.init(x:1,y:0),right:.zero,at:1).isEmpty,"first"); check(m.sample(left:.init(x:1,y:0),right:.zero,at:1).isEmpty,"same time"); check(m.sample(left:.init(x:1,y:0),right:.zero,at:0).isEmpty,"reversed") }
        scenario("gamepad-sleep-gap-is-capped") { var m = GamepadMapping(); _=m.configure(enabled:true,gameInFront:false); _=m.sample(left:.zero,right:.zero,at:0); check(m.sample(left:.init(x:1,y:0),right:.zero,at:100) == [.pointer(.init(x:50,y:0))],"50ms cap") }
        scenario("gamepad-trigger-hysteresis") { var m = GamepadMapping(); _=m.configure(enabled:true,gameInFront:false); check(m.trigger(left:true,value:0.6,desktopEnabled:true) == [.desktop(-1)],"threshold"); check(m.trigger(left:true,value:1,desktopEnabled:true).isEmpty,"held"); _=m.trigger(left:true,value:0.2,desktopEnabled:true); check(m.trigger(left:true,value:0.6,desktopEnabled:true) == [.desktop(-1)],"rearmed") }
        scenario("gamepad-game-and-disconnect-reset") { var m = GamepadMapping(); _=m.configure(enabled:true,gameInFront:false); check(m.configure(enabled:true,gameInFront:true) == [.releaseTriggers],"game"); check(m.disconnect().isEmpty,"idempotent"); _=m.configure(enabled:true,gameInFront:false); check(m.disconnect() == [.releaseTriggers],"unplug") }
        scenario("pin-fixed-window") { var p = PairingAttemptWindow(); check(try p.open(at:1,makePIN:{"0123"}) == "0123","leading zero"); check(p.deadline == 61,"expiry"); check(p.mayAttempt(at:60.99),"active"); check(!p.mayAttempt(at:61),"expired") }
        scenario("pin-invalid-inputs") { var p=PairingAttemptWindow(); rejects("not digits") { _=try p.open(at:0,makePIN:{"一234"}) }; rejects("negative time") { _=try p.open(at:-1,makePIN:{"1234"}) }; rejects("nan") { _=try p.open(at:.nan,makePIN:{"1234"}) } }
        scenario("pin-no-overlapping-window") { var p=PairingAttemptWindow(); _=try p.open(at:0,makePIN:{"1234"}); rejects("already open") { _=try p.open(at:1,makePIN:{"5678"}) } }
        scenario("pin-three-failures-cooldown") { var p=PairingAttemptWindow(); _=try p.open(at:0,makePIN:{"1234"}); for n in 1...3 { try p.failed(at:Double(n)) }; check(p.cooldownUntil == 303,"300 sec"); p.cancel(); rejects("cancel not bypass") { _=try p.open(at:302,makePIN:{"5678"}) }; check(try p.open(at:303,makePIN:{"5678"}) == "5678","boundary") }
        scenario("pin-restart-and-success") { var p=PairingAttemptWindow(restartedWithIncompleteAttempt:true,at:5); rejects("restart cool down") { _=try p.open(at:100,makePIN:{"1234"}) }; _=try p.open(at:305,makePIN:{"1234"}); try p.finish(at:306); check(!p.mayAttempt(at:307),"closed after success") }
        scenario("tlv-roundtrip-fragment-boundaries") { for n in [0,1,254,255,256,510,511,1024] { let d=Data(repeating:7,count:n); check(try PairingTLV.decode(PairingTLV.encode([(1,d)]),allowed:[1])[1] == d,"length \(n)") } }
        scenario("tlv-reject-malformed") { for bytes:[UInt8] in [[1],[1,2,8],[1,0,1,0],[9,0],[1,1,2,2,0,1,1,3]] { rejects("invalid tlv") { _=try PairingTLV.decode(Data(bytes),allowed:[1,2]) } } }
        scenario("tlv-bounds-and-duplicate-encoding") { rejects("big decode") { _=try PairingTLV.decode(Data(repeating:0,count:65_537),allowed:[0]) }; rejects("big encode") { _=try PairingTLV.encode([(1,Data(repeating:0,count:65_536))]) }; rejects("duplicate") { _=try PairingTLV.encode([(1,Data()),(1,Data())]) } }
        let session = RemoteEventRouter.Session(peer:"fixture-peer",epoch:1,keyRevision:1)
        scenario("router-no-session") { var r=RemoteEventRouter(); rejects("unverified") { _=try r.route(.cancel,session:session,sequence:0) } }
        scenario("router-events-and-sequence") { var r=RemoteEventRouter(); try r.begin(session); check(try r.route(.touch("begin",0,1),session:session,sequence:0) == .touch("begin",0,1),"touch"); check(try r.route(.button("tv","down"),session:session,sequence:1) == .button("tv","down"),"button"); check(try r.route(.clickOnly("playPause"),session:session,sequence:2) == .clickOnly("playPause"),"click") }
        scenario("router-replay-revokes") { var r=RemoteEventRouter(); try r.begin(session); _=try r.route(.cancel,session:session,sequence:0); rejects("replay") { _=try r.route(.cancel,session:session,sequence:0) }; check(r.session == nil,"revoked"); rejects("no revival") { try r.begin(session) } }
        scenario("router-gap-revokes") { var r=RemoteEventRouter(); try r.begin(session); rejects("gap") { _=try r.route(.cancel,session:session,sequence:1) }; check(r.session == nil,"revoked") }
        scenario("router-malformed-touch") { var r=RemoteEventRouter(); try r.begin(session); rejects("nan coordinate") { _=try r.route(.touch("move",.nan,0),session:session,sequence:0) }; check(r.session == nil,"revoked") }
        scenario("router-stale-peer") { var r=RemoteEventRouter(); try r.begin(session); rejects("old identity") { _=try r.route(.cancel,session:.init(peer:"other",epoch:1,keyRevision:1),sequence:0) }; check(r.session == session,"different caller doesn't consume sequence") }
        scenario("input-every-required-gate") { var a=WS2InputEligibility(); check(!a.mayIntercept,"default"); a.enabled=true; a.deviceConnected=true; a.permitted=true; a.unlocked=true; a.qualifiedPerEventSource=true; check(a.mayIntercept,"all true"); for key in 0..<7 { var b=a; switch key {case 0:b.enabled=false;case 1:b.deviceConnected=false;case 2:b.permitted=false;case 3:b.unlocked=false;case 4:b.qualifiedPerEventSource=false;case 5:b.tapHealthy=false;default:b.excludedApp=true};check(!b.mayIntercept,"gate \(key)") }; a.competingTool="其他工具";check(!a.mayIntercept,"competitor") }
        let dev=HIDMappingTransaction.Device(registryID:1,vendor:1452,product:789), empty=Data("[]".utf8), mapped=Data("[{\"x\":1}]".utf8)
        scenario("hid-unique-match-required") { var m=HIDMappingTransaction(); rejects("none") { _=try m.prepare(device:dev,matches:[],current:empty,replacement:mapped) }; rejects("multiple") { _=try m.prepare(device:dev,matches:[dev,dev],current:empty,replacement:mapped) } }
        scenario("hid-write-readback-restore") { var m=HIDMappingTransaction(); let w=try m.prepare(device:dev,matches:[dev],current:empty,replacement:mapped); check(m.active == nil,"no speculative ownership"); rejects("bad readback") { try m.commit(w,readback:empty) }; try m.commit(w,readback:mapped); let undo=try m.restore(device:dev,current:mapped); check(undo.replacement == empty,"original preserved"); try m.restored(undo,readback:empty); check(m.active == nil,"cleared") }
        scenario("hid-third-party-change-preserved") { var m=HIDMappingTransaction(); let w=try m.prepare(device:dev,matches:[dev],current:empty,replacement:mapped);try m.commit(w,readback:mapped);rejects("changed") { _=try m.restore(device:dev,current:Data("[2]".utf8)) };check(m.active != nil,"not falsely restored") }
        scenario("lock-url-exact-only") { check(WS2LockRequestPolicy.accepts(URL(string:"windowshade://lock")!),"accept");for s in ["windowshade://unlock","windowshade://lock?x=1","windowshade://lock/anything","windowshade://u@lock","windowshade://lock:12"] {check(!WS2LockRequestPolicy.accepts(URL(string:s)!),s)} }
        scenario("lock-origin-not-authentication") { var m=WS2LockRequestPolicy();let id=UUID();_=m.begin(origin:.localLink,at:0,id:id);m.observedLocked(provedRequestID:id,at:1);check(m.ownedLock == nil,"URL has no ownership") }
        scenario("lock-proved-current-presence") { var m=WS2LockRequestPolicy();let id=UUID();_=m.begin(origin:.presence,at:0,id:id);m.observedLocked(provedRequestID:id,at:1);check(m.ownedLock == id,"owned only matching backend ack");m.cancel();check(m.ownedLock == nil,"cancel") }
        scenario("lock-late-or-foreign-ack") { for (age,id) in [(6.0,Optional<UUID>.none),(6.0,UUID()),(1.0,UUID())] { var m=WS2LockRequestPolicy();_=m.begin(origin:.presence,at:0,id:UUID());m.observedLocked(provedRequestID:id,at:age);check(m.ownedLock == nil,"unowned") } }
        let source=Data(#"{"theme":"keep","hooks":{"Stop":[{"matcher":"","hooks":[{"type":"command","command":"other","timeout":7}]}]}}"#.utf8)
        scenario("hook-preview-preserves-third-party") { let p=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws hook'fixture",connected:true,provider:"claude");let o=try JSONSerialization.jsonObject(with:p.replacement) as! [String:Any];check(o["theme"] as? String == "keep","unknown root");check(String(data:p.replacement,encoding:.utf8)!.contains("other"),"third party");check(p.command.contains("'\\''"),"shell quote") }
        scenario("hook-preview-idempotence") { let p=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws-hook",connected:true,provider:"claude");let q=try WS2HookConfiguration.preview(original:p.replacement,executable:"/tmp/ws-hook",connected:true,provider:"claude");check(p.replacement == q.replacement,"idempotent") }
        scenario("hook-remove-only-owned") { let p=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws-hook",connected:true,provider:"claude");let q=try WS2HookConfiguration.preview(original:p.replacement,executable:"/tmp/ws-hook",connected:false,provider:"claude");let text=String(data:q.replacement,encoding:.utf8)!;check(text.contains("other"),"other remains");check(!text.contains("/tmp/ws-hook"),"owned removed") }
        scenario("hook-codex-unsupported-and-path-validation") { rejects("no guessed codex config") { _=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws-hook",connected:true,provider:"codex") };rejects("relative") { _=try WS2HookConfiguration.preview(original:source,executable:"relative",connected:true,provider:"claude") } }
        scenario("config-real-write-backup-rollback") { let f=temp.appendingPathComponent("settings.json");try source.write(to:f);let p=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws-hook",connected:true,provider:"claude");let backup=try WS2AtomicConfiguration.commit(p,to:f,confirmed:true);check(try Data(contentsOf:backup)==source,"backup");check(try Data(contentsOf:f)==p.replacement,"replacement");var st=stat();_=lstat(f.path,&st);check(st.st_mode & 0o777 == 0o600,"mode600");_=try WS2AtomicConfiguration.rollback(from:backup,expected:p.replacement,destination:f,confirmed:true);check(try Data(contentsOf:f)==source,"restored") }
        scenario("config-stale-preview-does-not-overwrite") { let f=temp.appendingPathComponent("stale.json");try Data("{}".utf8).write(to:f);let p=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws-hook",connected:true,provider:"claude");rejects("stale") { _=try WS2AtomicConfiguration.commit(p,to:f,confirmed:true) };check(try Data(contentsOf:f)==Data("{}".utf8),"preserved") }
        scenario("config-no-consent") { let f=temp.appendingPathComponent("consent.json");try source.write(to:f);let p=try WS2HookConfiguration.preview(original:source,executable:"/tmp/ws-hook",connected:true,provider:"claude");rejects("consent") { _=try WS2AtomicConfiguration.commit(p,to:f,confirmed:false) };check(try Data(contentsOf:f)==source,"unchanged") }
        scenario("config-symlink-rejected") { let target=temp.appendingPathComponent("target.json"), link=temp.appendingPathComponent("link.json");try source.write(to:target);try FileManager.default.createSymbolicLink(at:link,withDestinationURL:target);rejects("symlink") { _=try WS2AtomicConfiguration.readRegular(link.path) } }
        scenario("config-hardlink-rejected") { let f=temp.appendingPathComponent("hard1.json"),g=temp.appendingPathComponent("hard2.json");try source.write(to:f);check(link(f.path,g.path)==0,"created fixture");rejects("hardlink") { _=try WS2AtomicConfiguration.readRegular(g.path) } }
        scenario("config-new-does-not-replace-existing") { let f=temp.appendingPathComponent("new.json");try WS2AtomicConfiguration.createNew(source,to:f,confirmed:true);check(try Data(contentsOf:f)==source,"created");rejects("exists") { try WS2AtomicConfiguration.createNew(Data("{}".utf8),to:f,confirmed:true) };check(try Data(contentsOf:f)==source,"preserved") }
        scenario("socket-real-request-reply-and-cleanup") { let path=temp.appendingPathComponent("a.sock").path;let listener=try WS2UnixSocket.listen(at:path);let client=try WS2UnixSocket.connect(to:path);let server=try listener.accept(deadline:ProcessInfo.processInfo.systemUptime+1);try client.sendLine(Data("{\"id\":1}".utf8),deadline:ProcessInfo.processInfo.systemUptime+1);check(try server.readLine(deadline:ProcessInfo.processInfo.systemUptime+1)==Data("{\"id\":1}".utf8),"received");try server.sendLine(Data("{}".utf8),deadline:ProcessInfo.processInfo.systemUptime+1);check(try client.readLine(deadline:ProcessInfo.processInfo.systemUptime+1)==Data("{}".utf8),"reply");client.closeSocket();server.closeSocket();listener.closeSocket();check(!FileManager.default.fileExists(atPath:path),"own inode removed") }
        scenario("socket-occupied-not-unlinked") { let p=temp.appendingPathComponent("occupied.sock");try source.write(to:p);rejects("occupied") { _=try WS2UnixSocket.listen(at:p.path) };check(try Data(contentsOf:p)==source,"foreign path retained") }
        scenario("socket-timeout-bounded") { let path=temp.appendingPathComponent("timeout.sock").path;let server=try WS2UnixSocket.listen(at:path);defer{server.closeSocket()};let t=ProcessInfo.processInfo.systemUptime;rejects("accept timeout") { _=try server.accept(deadline:t+0.05) };check(ProcessInfo.processInfo.systemUptime-t < 1,"bounded") }
        scenario("socket-multiple-lines-and-size") { let path=temp.appendingPathComponent("two.sock").path;let l=try WS2UnixSocket.listen(at:path);let c=try WS2UnixSocket.connect(to:path);let s=try l.accept(deadline:ProcessInfo.processInfo.systemUptime+1);defer{c.closeSocket();s.closeSocket();l.closeSocket()};for text in ["a","b"]{try c.sendLine(Data(text.utf8),deadline:ProcessInfo.processInfo.systemUptime+1)};check(try s.readLine(deadline:ProcessInfo.processInfo.systemUptime+1)==Data("a".utf8),"first");check(try s.readLine(deadline:ProcessInfo.processInfo.systemUptime+1)==Data("b".utf8),"second");rejects("newline injection") { try c.sendLine(Data("x\ny".utf8),deadline:ProcessInfo.processInfo.systemUptime+1) };rejects("size") { try c.sendLine(Data(repeating:1,count:65_537),deadline:ProcessInfo.processInfo.systemUptime+1) } }
        scenario("socket-parent-mode-and-path-length") { let bad=temp.appendingPathComponent("bad");try FileManager.default.createDirectory(at:bad,withIntermediateDirectories:false,attributes:[.posixPermissions:0o755]);rejects("bad parent") { _=try WS2UnixSocket.listen(at:bad.appendingPathComponent("x.sock").path) };rejects("long path") { _=try WS2UnixSocket.listen(at:temp.appendingPathComponent(String(repeating:"x",count:160)).path) } }
        scenario("stdin-bounded-read-and-eof") { let p=Pipe();try p.fileHandleForWriting.write(contentsOf:Data("abcdef".utf8));try p.fileHandleForWriting.close();check(try WS2BoundedInput.readAll(fd:p.fileHandleForReading.fileDescriptor,deadline:ProcessInfo.processInfo.systemUptime+1)==Data("abcdef".utf8),"all bytes");try p.fileHandleForReading.close() }
        scenario("stdin-size-limit") { let p=Pipe();try p.fileHandleForWriting.write(contentsOf:Data("abc".utf8));try p.fileHandleForWriting.close();rejects("limit") { _=try WS2BoundedInput.readAll(fd:p.fileHandleForReading.fileDescriptor,maximum:2,deadline:ProcessInfo.processInfo.systemUptime+1) };try p.fileHandleForReading.close() }
        scenario("process-actual-fragmented-fake-response") { let c=try WS2ProcessChannel(executable:URL(fileURLWithPath:CommandLine.arguments[2]),arguments:[root.appendingPathComponent("tests/fake-backend.py").path],workingDirectory:temp,environment:["PATH":"/usr/bin:/bin"]);try c.start();defer{c.stop()};try c.send(Data(#"{"id":7,"params":{"text":"fixture"}}"#.utf8),deadline:ProcessInfo.processInfo.systemUptime+2);let data=try c.readLine(deadline:ProcessInfo.processInfo.systemUptime+2);let r=try JSONSerialization.jsonObject(with:data) as! [String:Any];check(r["id"] as? Int == 7,"correlation");check(String(data:data,encoding:.utf8)!.contains("fixture"),"echo") }
        scenario("process-timeout-and-stop-idempotence") { let c=try WS2ProcessChannel(executable:URL(fileURLWithPath:CommandLine.arguments[2]),arguments:[root.appendingPathComponent("tests/fake-backend.py").path],workingDirectory:temp,environment:[:]);try c.start();try c.send(Data(#"{"method":"hang"}"#.utf8),deadline:ProcessInfo.processInfo.systemUptime+1);rejects("deadline") { _=try c.readLine(deadline:ProcessInfo.processInfo.systemUptime+0.05) };c.stop();c.stop();check(c.stopped,"stopped");rejects("closed") { try c.send(Data("{}".utf8),deadline:ProcessInfo.processInfo.systemUptime+1) } }
        func ingest(_ wire: inout CodexWire,_ text:String) throws { _ = try wire.ingest(Data((text+"\n").utf8),now:.zero) }
        func ready() throws -> CodexWire {
            var w=CodexWire();try w.initialize(now:.zero);_=w.drain()
            try ingest(&w,#"{"id":1,"result":{}}"#);_=w.drain()
            try ingest(&w,#"{"id":2,"result":{"data":[{"model":"fixture","supportedReasoningEfforts":[{"reasoningEffort":"high"}]}],"nextCursor":null}}"#)
            return w
        }
        func threaded() throws -> CodexWire {
            var w=try ready();try w.resumeThread(id:"thread-fixture",now:.zero);_=w.drain()
            try ingest(&w,#"{"id":3,"result":{"thread":{"id":"thread-fixture"}}}"#);return w
        }
        scenario("codex-resume-pinned-field") { var w=try ready();try w.resumeThread(id:"thread-fixture",now:.zero);let messages=w.drain();check(messages.count==1,"one request");let text=String(data:messages[0],encoding:.utf8)!;check(text.contains("thread/resume")&&text.contains("threadId"),"pinned field");try ingest(&w,#"{"id":3,"result":{"thread":{"id":"thread-fixture"}}}"#);check(w.threadID=="thread-fixture","resumed");try messages[0].write(to:root.appendingPathComponent("validation/resume-request.ndjson")) }
        scenario("codex-resume-wrong-thread-closes") { var w=try ready();try w.resumeThread(id:"wanted",now:.zero);rejects("wrong thread") { try ingest(&w,#"{"id":3,"result":{"thread":{"id":"other"}}}"#) };check(w.state == .closed,"closed") }
        scenario("codex-thread-start-resume-exclusion") { var w=try ready();try w.resumeThread(id:"wanted",now:.zero);rejects("start while resume") { try w.startThread(cwd:"/fixture",model:"fixture",now:.zero) };rejects("second resume") { try w.resumeThread(id:"another",now:.zero) } }
        scenario("codex-early-turn-started-allows-current-approval") { var w=try threaded();try w.startTurn(text:"fixture",model:"fixture",effort:"high",now:.zero);_=w.drain();try ingest(&w,#"{"method":"turn/started","params":{"threadId":"thread-fixture","turn":{"id":"t1"}}}"#);check(w.turnID=="t1","announced");try ingest(&w,#"{"id":"approval1","method":"item/commandExecution/requestApproval","params":{"threadId":"thread-fixture","turnId":"t1","itemId":"i1"}}"#);check(w.approvals.count==1,"current approval");try ingest(&w,#"{"id":4,"result":{"turn":{"id":"t1"}}}"#);check(w.turnID=="t1","reply consistent") }
        scenario("codex-completion-clears-approval-and-late-start-reply") { var w=try threaded();try w.startTurn(text:"fixture",model:"fixture",effort:"high",now:.zero);_=w.drain();try ingest(&w,#"{"method":"turn/started","params":{"threadId":"thread-fixture","turn":{"id":"t1"}}}"#);try ingest(&w,#"{"id":"approval1","method":"item/fileChange/requestApproval","params":{"threadId":"thread-fixture","turnId":"t1","itemId":"i1"}}"#);try ingest(&w,#"{"method":"turn/completed","params":{"threadId":"thread-fixture","turn":{"id":"t1"}}}"#);check(w.approvals.isEmpty,"cleared");check(w.turnID == nil,"finished");try ingest(&w,#"{"id":4,"result":{"turn":{"id":"t1"}}}"#);check(w.turnID == nil,"late result cannot resurrect") }
        scenario("codex-announcement-reply-mismatch-closes") { var w=try threaded();try w.startTurn(text:"fixture",model:"fixture",effort:"high",now:.zero);_=w.drain();try ingest(&w,#"{"method":"turn/started","params":{"threadId":"thread-fixture","turn":{"id":"t1"}}}"#);rejects("mismatched id") { try ingest(&w,#"{"id":4,"result":{"turn":{"id":"t2"}}}"#) };check(w.state == .closed,"closed") }
        scenario("pin-cancel-reopen-retains-failures") { var p=PairingAttemptWindow();_=try p.open(at:0,makePIN:{"1234"});try p.failed(at:1);try p.failed(at:2);p.cancel();_=try p.open(at:3,makePIN:{"5678"});try p.failed(at:4);check(p.cooldownUntil==304,"reopening does not reset failure budget") }
        scenario("multitouch-symbols-not-enough") { let q=MultitouchQualification(systemBuild:"fixture",architecture:"arm64",recordStride:64,fieldOffsets:["identifier":0,"state":4,"x":8,"y":16,"timestamp":24],callbackEncoding:"fixture-not-real",sourceDigest:String(repeating:"a",count:64),reviewedOnDevice:false);check(!q.permits(build:"fixture",architecture:"arm64",sourceDigest:String(repeating:"a",count:64)),"review missing");check(!q.permits(build:"other",architecture:"arm64",sourceDigest:String(repeating:"a",count:64)),"build mismatch") }
        let summary:[String:Any]=["scenarios":scenarios,"assertions":assertions,"failures":failures,"cases":output]
        try JSONSerialization.data(withJSONObject:summary,options:[.prettyPrinted,.sortedKeys]).write(to:root.appendingPathComponent("validation/core-results.json"))
        print("\(failures == 0 ? "PASS" : "FAIL") part3 core: \(scenarios) scenarios, \(assertions) assertions, \(failures) failures")
        if failures > 0 { exit(1) }
    }
}
