// 由 tools/privacy/make-privacy-page-source.py 从 tools/privacy/registry.json 生成；不要手改。
// 只有 status=current 的行会出现在设置里；planned 行等对应功能接通再说。
import Foundation

struct WS2PrivacyRow: Sendable {
    let id: String
    let label: String
    /// public / sensitive / private：private 的值默认不展开。
    let sensitivity: String
    let group: String
    let reads: String
    let purpose: String
    let destination: String
    let activation: String
    let toggle: String
    /// 登记表里这类读取用到的接口名；「显示技术细节」打开后才看得到。
    let interfaces: [String]
}

enum WS2PrivacyData {
    static let groupOrder: [String] = ["不用问就能读", "你同意后才读", "系统未公开的方法", "去了哪里"]

    static let rows: [WS2PrivacyRow] = [
        WS2PrivacyRow(
            id: "screen-shape",
            label: "屏幕和刘海的形状",
            sensitivity: "public",
            group: "不用问就能读",
            reads: "显示器编号、尺寸、菜单栏与安全区",
            purpose: "把控件放在所属屏幕",
            destination: "内存；不发送",
            activation: "布局启用时；隐私页仅取现有快照",
            toggle: "无独立开关，跟随刘海功能",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "lock-state",
            label: "是否锁屏",
            sensitivity: "sensitive",
            group: "不用问就能读",
            reads: "锁定/未锁定/未知、当前控制台会话",
            purpose: "阻止锁屏时显示或执行敏感动作",
            destination: "内存；不发送",
            activation: "会话通知与授权边界复核",
            toggle: "安全边界不可单独关闭",
            interfaces: ["CGSSessionScreenIsLocked", "CGSessionCopyCurrentDictionary"],
        ),
        WS2PrivacyRow(
            id: "battery",
            label: "配件电量",
            sensitivity: "sensitive",
            group: "不用问就能读",
            reads: "已连接配件型号、电量、连接状态",
            purpose: "显示现有配件状态",
            destination: "内存；不发送",
            activation: "现有活动来源；页面不再轮询",
            toggle: "跟随实时活动；不新增重复开关",
            interfaces: ["IOServiceMatching"],
        ),
        WS2PrivacyRow(
            id: "recording-app",
            label: "哪个 App 在录音",
            sensitivity: "sensitive",
            group: "不用问就能读",
            reads: "音频进程标识、bundle ID、录音状态",
            purpose: "录音活动提示，不读取录音内容",
            destination: "内存；不发送",
            activation: "现有来源激活时",
            toggle: "实时活动",
            interfaces: ["kAudioHardwarePropertyProcessObjectList"],
        ),
        WS2PrivacyRow(
            id: "window-ax",
            label: "窗口的标题、位置和大小",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "AX 标题、窗口ID、角色、几何、所属进程",
            purpose: "找到并收起或恢复目标窗口",
            destination: "内存；已收起窗口的恢复日志存本机",
            activation: "执行动作或既有缓存刷新",
            toggle: "辅助功能授权；关闭功能停止新增读取",
            interfaces: ["AXUIElementCopyAttributeValue"],
        ),
        WS2PrivacyRow(
            id: "key-position",
            label: "按了哪个键",
            sensitivity: "sensitive",
            group: "你同意后才读",
            reads: "键码、修饰键、按下/松开、点击/滚动位置",
            purpose: "快捷键、惯用键和手势；不读输入文字",
            destination: "内存；不持久按键序列",
            activation: "功能启用且未锁定",
            toggle: "既有惯用键/手势开关；一直用Mac时关闭相应钩子",
            interfaces: ["CGEvent.tapCreate"],
        ),
        WS2PrivacyRow(
            id: "window-image",
            label: "窗口的画面",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "授权目标窗口的像素帧与缩略图",
            purpose: "动画、预览和窗口浏览",
            destination: "目标为仅内存；磁盘行为待P1-FS验证",
            activation: "只有可见动画/预览",
            toggle: "屏幕录制授权；对应功能",
            interfaces: ["SCScreenshotManager", "SCShareableContent", "SCStream"],
        ),
        WS2PrivacyRow(
            id: "camera-frame",
            label: "摄像头",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "临时视频帧、动作/是否有人结果",
            purpose: "用户触发的眨眼转头；离席检测另按L1合同",
            destination: "只在内存；无主动上传；需真机文件检查",
            activation: "功能显式开启且当前状态允许",
            toggle: "摄像头及对应功能；锁屏不自动重开一般摄像头源",
            interfaces: ["AVCaptureDevice", "AVCaptureSession", "VNDetectFaceLandmarksRequest"],
        ),
        WS2PrivacyRow(
            id: "music",
            label: "正在播放的歌",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "曲目、艺人、封面入口、进度、播放状态",
            purpose: "显示音乐并控制本次暂停的播放器",
            destination: "进程间自动化；内存；不把标题写日志",
            activation: "通知触发，现有兜底计时不在本轮更改",
            toggle: "实时活动/音乐控制和系统自动化授权",
            interfaces: ["osascript"],
        ),
        WS2PrivacyRow(
            id: "notch-private",
            label: "刘海的精确轮廓",
            sensitivity: "public",
            group: "系统未公开的方法",
            reads: "bezelPath、轮廓和圆角数据",
            purpose: "贴合硬件边缘",
            destination: "内存",
            activation: "显示变化时缓存",
            toggle: "关闭自适应外形用公开安全区",
            interfaces: ["bezelPath"],
        ),
        WS2PrivacyRow(
            id: "spaces-private",
            label: "其他桌面和最小化窗口的画面",
            sensitivity: "private",
            group: "系统未公开的方法",
            reads: "私有窗口/Space关系、位置和透明度，以及可用的窗口像素",
            purpose: "已授权的跨桌面预览及窗口控制；枚举或控制调用不一定读取像素",
            destination: "内存；磁盘行为待验证",
            activation: "用户动作时",
            toggle: "私有截图退回公开可用窗口/关闭预览",
            interfaces: ["CGSHWCaptureWindowList", "CGSMainConnectionID", "SLSCopyManagedDisplaySpaces", "SLSCopyManagedDisplaySpacesFunction", "SLSCopySpacesForWindows", "SLSCopySpacesForWindowsFunction", "SLSGetWindowAlpha", "SLSGetWindowAlphaFunction", "SLSHideSpaces", "SLSMainConnectionID", "SLSMainConnectionIDFunction", "SLSManagedDisplay", "SLSManagedDisplayGetCurrentSpace", "SLSManagedDisplayGetCurrentSpaceFunction", "SLSManagedDisplaySetCurrentSpace", "SLSManagedDisplaySetCurrentSpaceFunction", "SLSMoveWindowWithGroup", "SLSMoveWindowWithGroupFunction", "SLSMoveWindowsToManagedSpace", "SLSMoveWindowsToManagedSpaceFunction", "SLSReassociateWindowsSpacesByGeometry", "SLSReassociateWindowsSpacesByGeometryFunction", "SLSRemoveWindowsFromSpaces", "SLSSetWindowAlpha", "SLSSetWindowAlphaFunction", "SLSShowSpaces", "SLSSpaceAddWindowsAndRemoveFromSpaces", "SLSSpaceCreate", "SLSSpaceSetAbsoluteLevel"],
        ),
        WS2PrivacyRow(
            id: "hinge",
            label: "屏幕开合的角度",
            sensitivity: "sensitive",
            group: "系统未公开的方法",
            reads: "HID 铰链角度",
            purpose: "桌面开合效果",
            destination: "内存",
            activation: "现有运动分档采样，锁屏按现有边界",
            toggle: "桌面开合",
            interfaces: ["IOHIDDevice", "IOHIDDeviceClose", "IOHIDDeviceGetReport", "IOHIDDeviceOpen", "IOHIDManager", "IOHIDManagerActivate", "IOHIDManagerCancel", "IOHIDManagerClose", "IOHIDManagerCopyDevices", "IOHIDManagerCreate", "IOHIDManagerExtRelease", "IOHIDManagerOpen", "IOHIDManagerRegisterInputReportCallback", "IOHIDManagerSetDeviceMatching", "IOHIDManagerSetDispatchQueue"],
        ),
        WS2PrivacyRow(
            id: "tilt",
            label: "机身的倾斜",
            sensitivity: "sensitive",
            group: "系统未公开的方法",
            reads: "加速度计样本、移动状态",
            purpose: "桌面倾斜及铰链采样分档",
            destination: "内存",
            activation: "驱动推送，停用后拆回调",
            toggle: "倾斜效果",
            interfaces: ["IOHIDDevice", "IOHIDManager", "IOHIDManagerActivate", "IOHIDManagerCancel", "IOHIDManagerClose", "IOHIDManagerCopyDevices", "IOHIDManagerCreate", "IOHIDManagerOpen", "IOHIDManagerRegisterInputReportCallback", "IOHIDManagerSetDeviceMatching", "IOHIDManagerSetDispatchQueue", "IOServiceMatching"],
        ),
        WS2PrivacyRow(
            id: "update",
            label: "检查更新",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "应用版本、Sparkle更新请求及服务端可见网络元数据",
            purpose: "取得更新目录和下载",
            destination: "更新服务；实际主机从构建配置和P2流量核验",
            activation: "仅自动更新开关或用户检查更新",
            toggle: "自动检查更新；关后仍可手动检查",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "settings",
            label: "设置",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "本应用用户选择、已授权开关、模型槽位标识及被查询的系统偏好",
            purpose: "保留选择和适应当前系统设置",
            destination: "本机偏好文件；不存临时审批票据",
            activation: "原控制器需要查询时；页面只读已有快照",
            toggle: "各原有设置；重置只清本应用值",
            interfaces: ["UserDefaults"],
        ),
        WS2PrivacyRow(
            id: "recovery",
            label: "恢复记录",
            sensitivity: "private",
            group: "去了哪里",
            reads: "收起窗口目标、标题和位置等恢复字段",
            purpose: "崩溃后放回用户窗口",
            destination: "本机 RecoveryJournal.plist；恢复后的删减需单独核验",
            activation: "收起/恢复事务",
            toggle: "无删除其他App数据行为",
            interfaces: ["RecoveryJournal"],
        ),
        WS2PrivacyRow(
            id: "diagnostics",
            label: "运行记录",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "固定事件码、技术状态、耗时；禁止窗口标题和提示词",
            purpose: "排错与性能核验",
            destination: "本机专用目录0700/文件0600及一个备份",
            activation: "事件发生时；不开新轮询",
            toggle: "开发路径覆盖受同样安全规则限制",
            interfaces: [],
        ),
        WS2PrivacyRow(
            id: "login-item",
            label: "登录时自动启动",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "本应用登录项状态",
            purpose: "按用户选择启动",
            destination: "本机系统登录项服务",
            activation: "打开设置读取既有状态，修改时提交",
            toggle: "既有登录时自动启动",
            interfaces: ["SMAppService"],
        ),
        WS2PrivacyRow(
            id: "authorization-key",
            label: "设备授权密钥",
            sensitivity: "private",
            group: "你同意后才读",
            reads: "Secure Enclave 包裹的句柄、公钥、指纹集合状态摘要、一次性挑战及签名结果；不导出私钥",
            purpose: "用途和目标绑定的一次性授权账",
            destination: "~/Library/Application Support/WindowShade/Authorization/ 下的 device-key.v1、.pub、.biometry 文件及内存；当前源码没有把句柄写入 Keychain",
            activation: "每次明确授权；锁屏等推进代次",
            toggle: "删除登记；安全校验不可跳过",
            interfaces: ["LAContext", "SecAccessControlCreateWithFlags", "SecureEnclave", "biometryState", "evaluatedPolicyDomainState", "stateHash"],
        ),
        WS2PrivacyRow(
            id: "focus-preferences",
            label: "番茄钟的设置",
            sensitivity: "sensitive",
            group: "去了哪里",
            reads: "专注时长（25/5 或 50/10）与「专注时收起聊天窗口」",
            purpose: "按你选的时长计时；收窗开关只在窗口所有权适配器就绪后生效",
            destination: "本机偏好；不发送",
            activation: "打开设置、改选项或开始计时时",
            toggle: "设置里的番茄钟两项",
            interfaces: [],
        ),
    ]
}
